# -*- coding: utf-8 -*-
# Generated by Django 1.9c2 on 2015-12-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('office_or_home', models.CharField(max_length=50)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'diary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JourneyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(blank=True, max_length=20, null=True)),
                ('destination', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('journey_time', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journey_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tutorials',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
